name: Build APK and Upload to S3

on:
  push:
    branches:
      - master  # Trigger workflow on push to the main branch

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    
    

    - name: Build APK
      run: |
        cd /home/ubuntu/project/automated-build-android-app-with-github-action  # Replace with your project's path
        ./gradlew assembleRelease

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Upload APK to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'  # Replace with your AWS region
      run: |
        aws s3 cp /home/ubuntu/project/automated-build-android-app-with-github-action/app/build/outputs/apk/release/app-release.apk s3://apkbucket1/android-apks/ --acl public-read
