---
name: Build APK and Upload to S3
on:
  push:
    branches:
      - master
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
      - name: Verify Java Version
        run: java -version
      - name: Build APK
        run: |
          cd ${{ github.workspace }}
          ./gradlew assembleRelease
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Debug AWS Environment Variables
        run: |
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_REGION: $AWS_REGION"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: us-east-1
      - name: Check current directory
        run: |
          echo "Current directory: $PWD"
      - name: Debug Directory
        run: ls -l $PWD
      - name: Debug All Files
        run: find $PWD
      - name: Find APK
        run: |
          APK_PATH=$(find $PWD -name "*.apk" | head -n 1)
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
      - name: Debug APK Path
        run: |
          echo "APK_PATH: $APK_PATH"
          ls -l "$(dirname "$APK_PATH")"
      - name: List Generated Files
        run: |
          echo "Current Directory: $PWD"
          find $PWD -name "*.apk"
      - name: Set APK_PATH
        run: |
          APK_FILE=$(find $PWD -name "*.apk" | head -n 1)
          if [ -z "$APK_FILE" ]; then
          echo "Error: No APK file found!"
          exit 1
          fi
          echo "APK_PATH=$APK_FILE" >> $GITHUB_ENV
          echo "Found APK:$APK_FILE"
      - name: Upload APK to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: >
          aws s3 cp "$APK_PATH/github-action-automated2.2.5-release.apk"
          s3://apkbucket1/android-apks/ --acl public-read --region $AWS_REGION
