name: Build APK and Upload to S3

on:
  push:
    branches:
      - master  # Replace with 'master' if your branch is named 'master'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java Version
        run: java -version

      - name: Build APK
        run: |
          cd ${{ github.workspace }}
          ./gradlew assembleRelease

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      
      - name: Move APK file
        run: |
          mv "/home/runner/work/automated-build-android-app-with-github-action/automated-build-android-app-with-github-action/app/build/outputs/apk/release/github-action-automated2.2.5-release.apk" \
          "/home/runner/work/_temp/github-action-automated-release.apk"
      - name: Debug AWS Environment Variables
        run: |
         echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
         echo "AWS_REGION: $AWS_REGION"
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_REGION: 'us-east-1'

      - name: Upload APK to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws s3 cp "/home/runner/work/_temp/github-action-automated-release.apk" \
          s3://apkbucket1/android-apks/ --acl public-read --region $AWS_REGION
